import { Articles } from 'components/Articles';
import Head from 'next/head';
import React from 'react';

const Blog = () => {
    return (
        <>
             <Head>
                <title>Riks | Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Articles />
        </>
    );
};

export default Blog;