import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import { Header, Articles } from 'components';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Riks Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <div className={styles.container}>
          <Articles />
        </div>
      </main>

      <footer className={styles.footer}>
          Saka Ricky &copy;
      </footer>
    </div>
  );
};

export default Home;
